volumes:
  prometheus_data: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-exporter.rule=Host(`node-exporter.${BASE_DOMAIN}`)"
      - "traefik.http.routers.node-exporter.entrypoints=websecure"
      - "traefik.http.routers.node-exporter.tls.certresolver=letsencrypt"
      - "traefik.docker.network=inverseproxy_shared"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      default:
      inverseproxy_shared:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.${BASE_DOMAIN}`)"
      - "traefik.http.routers.cadvisor.entrypoints=websecure"
      - "traefik.http.routers.cadvisor.tls.certresolver=letsencrypt"
      - "traefik.docker.network=inverseproxy_shared"
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    expose:
      - 8080
    networks:
      default:
      inverseproxy_shared:

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - default
    command: -config.file=/etc/promtail/config.yml

networks:
  default:
  inverseproxy_shared:
    external: true
